### ISSUE TITLE
No hyperlink from acronyms to List of Abbreviations

### ISSUE THREAD

**Issue by TYueksel** [latextemplates/scientific-thesis-template#102]
There are no hyperlinks from acronyms to the List of Abbreviations.
In the [begginers guide for the glossaries package](http://tug.ctan.org/macros/latex/contrib/glossaries/glossariesbegin.pdf) is stated:

> Take care if you use the glossaries package with hyperref. Contrary to the usual advice that hyperref should be loaded last, glossaries (and glossaries-extra) must be loaded after hyperref

I think this is not the case...

**Comment by Vogel612** [comment]
This diagnosis seems to be correct. `hyperref` is included on line 701 of config.tex: https://github.com/latextemplates/scientific-thesis-template/blob/398d3256333cc59c3fea8464ac14aad8d3c940af/config.tex#L701

`glossaries` is loaded on line 94. 

https://github.com/latextemplates/scientific-thesis-template/blob/398d3256333cc59c3fea8464ac14aad8d3c940af/config.tex#L94

A fix might be as simple as moving glossaries to below hyperref, as has previously been done with `algorithm`

**Comment by TYueksel** [comment]
Moving glossaries to below hyperref didn't help solving the problem. acronyms with \gls still dont link to the List of Abbreviations. By linking I mean that the displayed acronym isnt a link, which sends me to the to the List of Abbreviations by clicking on it

**Comment by koppor** [comment]
It used to work. Please help by using [git bisect](https://git-scm.com/docs/git-bisect) to find the commit where it stopped working. That would really help to fix the issue. With "latexmk" that shouldn't be an issue. However, it will certainly take more than 30 minutes to do.

**Comment by TYueksel** [comment]
I figured out a way myself to make this work. To fix this problem, you have to move not only glossaries, but line 84-105 to below hyperref. Those are the lines:

`\usepackage{ragged2e}`
`\usepackage{scrwfile}`
`\usepackage[acronym,indexonlyfirst,nomain]{glossaries}`
`\ifdeutsch`
`  \renewcommand*{\acronymname}{Abkürzungsverzeichnis}`
`\else`
`  \renewcommand*{\acronymname}{List of Abbreviations}`
`\fi`
`\renewcommand*{\glsgroupskip}{}`
`\makenoidxglossaries`

**Comment by koppor** [comment]
Could you please file a PR or reopen the issue? TYIA!

Am Fr., 11. Jan. 2019, 20:41 hat TYueksel <notifications@github.com>
geschrieben:
