### ISSUE TITLE
Italics and bold do not work in body text

### ISSUE THREAD

**Issue by datMaffin** [latextemplates/scientific-thesis-template#110]
Changing the body text to italic (with `\textit{}`) or bold (with `textbf{}`) does not result in an italic or bold text in the pdf.

I was able to fix it by changing the `\setmainfont` in https://github.com/latextemplates/scientific-thesis-template/blob/master/config.tex#L88 from
```tex
  \setmainfont{TeXGyreTermes-Regular}
```
 to 
```tex
  \setmainfont{TeXGyreTermes-Regular}[
       BoldFont       = TeXGyreTermes-Bold ,
       ItalicFont     = TeXGyreTermes-Italic ,
       BoldItalicFont = TeXGyreTermes-BoldItalic ]
```

**Comment by koppor** [comment]
Thank you for reporting and proposing a fix.

Could you please file a pull request?

**Comment by datMaffin** [comment]
Well, it was not my intention to already close the issue (I am going to reopen it again, if possible):

I am only available to verify the fix in the current MacTex / TexLive 2019. I do not have MikTex, which seems to be the officially supported platform for this template.

I created the pull request: https://github.com/latextemplates/scientific-thesis-template/pull/111
