### ISSUE TITLE
`kvoptions-patch.sty' not found on recent MikTeX

### ISSUE THREAD

**Issue by parttimehorse** [latextemplates/scientific-thesis-template#114]
I think kvoptions-patch.sty was removed from the most recent version of the oberdiek package that arrived in MikTeX yesterday, after an update today the template does not seem to want to build out of the box. I'm not really familiar with it, any tips for working around this?

**Comment by parttimehorse** [comment]
Ok so it seems like this isn't the only package that has gone missing recently, when commenting out 
`\RequirePackage{kvoptions-patch}`
it will ask for kvoptions, and if i download and add kvoptions.sty manually to the main folder, it will ask for stringenc.sty ...

**Comment by koppor** [comment]
Workaround: Use docker

    docker run --rm -v DIROFTEXDOCUMENT:/home danteev/texlive lualatex --shell-escape -synctex=1 -interaction=nonstopmode main-english

replace DIROFTEXDOCUMENT by the directory of your latex document. Example: c:\users\mylogin\documents\thesis

**Comment by koppor** [comment]
Works again today. Thus, I close this issue.
