### ISSUE TITLE
Problem with citing

### ISSUE THREAD

**Issue by pascalhuszar** [latextemplates/scientific-thesis-template#120]
Hey, i want to add this reference https://dl.acm.org/doi/book/10.5555/517162 into my thesis and cite it. But after i added and cite, the warrning 'undefinde' occur.
Here is the bib:
```
@book{10.5555/517162,
author = {Langer, Hagen},
title = {Parsing-Experimente},
year = {2001},
isbn = {3631371950},
publisher = {P. Lang Publishing Co.},
address = {USA}
}
```

Any suggestions? Except that, every bib works

**Comment by Vogel612** [comment]
Could you add how you cite in the latex file? What's the exact error message? What environment are you using and have you compiled twice to allow for the compiler to allocate the space required for citations?

**Comment by pascalhuszar** [comment]
I fixed the problem: i rerun biber over main-english.tex
Thanks anyway :)

**Comment by koppor** [comment]
@pascalhuszar You can also use `latexmk`, which is an advanced make automatically checking which latex tools should be run.
