### ISSUE TITLE
Additional Section in Main

### ISSUE THREAD

**Issue by pascalreisert** [latextemplates/scientific-thesis-template#127]
Could we add an additional section "Related Work" (in the german version "Verwandte Arbeiten") to main-english (respectively main-german)? (Either after "Introduction" or before "Conclusion and Outlook")

Recently, we had many students who did not include related work into their thesis. If this is included in the template, students will likely use it and if not, they have at least to think about why they do not need a "related work" section (e.g. because they include it in the intro).

Thanks in advance.

**Comment by koppor** [comment]
Sure. Please go ahead.

* Refs https://github.com/latextemplates/generator-latex-template/issues/19
* Refs <blockquote class="twitter-tweet"><p lang="en" dir="ltr">I just published a LaTeX template for writing your first scientific thesis (Bachelor end project, Master thesis) at <a href="https://twitter.com/TUeindhoven?ref_src=twsrc%5Etfw">@TUeindhoven</a> <a href="https://twitter.com/TUe_MCS?ref_src=twsrc%5Etfw">@TUe_MCS</a> to GitHub.<br>It provides guidance on how to structure scientific writing. <a href="https://t.co/Re9GKEkCEj">https://t.co/Re9GKEkCEj</a> <br>Fork, use, improve: pull request are welcome!</p>&mdash; Dirk Fahland (@dfahland) <a href="https://twitter.com/dfahland/status/1252246336617013248?ref_src=twsrc%5Etfw">April 20, 2020</a></blockquote> 

Extracted refs: 

1. Include a good structuring into https://github.com/latextemplates/generator-latex-template/
2. Regenerate this repo based on that.

**Comment by chriba** [comment]
I believe this issue can be closed now!

**Comment by koppor** [comment]
I left this open on purpose, because the very good text of https://github.com/dfahland/Master-or-Bachelor-thesis-Template-Eindhoven-University-of-Technology/blob/master/main.tex is not included yet. I planned to integrate it into the latex template generator (as shortly described in my comment above), but this did not happen yet.

#hacktoberfest?

**Comment by koppor** [comment]
Including long howtos depends on https://github.com/latextemplates/generator-latex-template/pull/67. For LNCS and IEEE, it already works. However, not for the scientific thesis template.

@chriba is right in saying that the original issue is solved - thus, I close this issue to keep the number of opened PRs low.
