### ISSUE TITLE
GitHub release missing for 3.0.0

### ISSUE THREAD

**Issue by Legion2** [latextemplates/scientific-thesis-template#133]
There is no proper GitHub release for version 3.0.0, so the current latest version is 2.5.0?

**Comment by koppor** [comment]
Interesting.

![grafik](https://user-images.githubusercontent.com/1366654/99909495-1702e580-2ce9-11eb-8f61-680903d7cb4f.png)

I'll press some buttons on GitHub now.

Should look better now.
