### ISSUE TITLE
Where can i assign section distance 

### ISSUE THREAD

**Issue by meda1028** [latextemplates/scientific-thesis-template#147]
Hey i want to adjust the distance between each section, subsection and paragraph.
I tried something like this with the titlesec package:
\titlespacing*{\section}
{0pt}{5.5ex plus 1ex minus .2ex}{4.3ex plus .2ex}
\titlespacing*{\subsection}
{0pt}{5.5ex plus 1ex minus .2ex}{4.3ex plus .2ex}
\titlespacing*{\subsubsection}
{0pt}{5.5ex plus 1ex minus .2ex}{4.3ex plus .2ex}
\titlespacing*{\paragraph}
{0pt}{5.5ex plus 1ex minus .2ex}{4.3ex plus .2ex}
but it just produced a bunch of errors

**Comment by Vogel612** [comment]
"a bunch of errors" is not really helpful for diagnosing... We wouldn't want to fix something else than what you're experiencing, right?

**Comment by meda1028** [comment]
Np, already fixed it.
For those who wonder the command I used was:
\redaclaresectioncommand
