### ISSUE TITLE
Travis build is broken

### ISSUE THREAD

**Issue by eiselems** [latextemplates/scientific-thesis-template#41]
Hey i just saw that the travis build errors out:

Only saw it is related to the installation of lvm2

**Comment by koppor** [comment]
We currently have no money to pay someone for that. Thus, it depends on the availability of our free time. - If you can spend some more time, we would like to encourage you to support us here or to check https://help.jabref.org/en/FAQcontributing - especially the part asking for improvement of the help pages <https://help.jabref.org/en/>. There are also plenty of open issues there: https://github.com/JabRef/help.jabref.org/issues/ - Helping in JabRef helps to free time for this project.

**Comment by koppor** [comment]
Installation hint for Ubuntu: https://github.com/scottkosty/install-tl-ubuntu

**Comment by eiselems** [comment]
Sadly I am no expert in setting up travis.
In addition to that i am busy writing my thesis :/
Otherwise I would try to fix it by myself

**Comment by koppor** [comment]
We successfully switched to CircleCI - see https://circleci.com/gh/latextemplates/scientific-thesis-template
