### ISSUE TITLE
Missing course 

### ISSUE THREAD

**Issue by sven-mayer** [latextemplates/scientific-thesis-template#47]
"Medieninformatik" is mission as a course type in the uni-stuttgart-cs-cover

**Comment by koppor** [comment]
Refs https://github.com/latextemplates/uni-stuttgart-computer-science-template/pull/44/commits/70edc6fcb89d18cac4b30148001727a621ef3326

**Comment by koppor** [comment]
This seems to be fixed.

Furthermore, according to https://github.com/latextemplates/uni-stuttgart-computer-science-cover/blob/master/README.md#supported-options, the course can be simply be given using `{Coursename}`.
