### ISSUE TITLE
Different font size English/German

### ISSUE THREAD

**Issue by sven-mayer** [latextemplates/scientific-thesis-template#48]
The font size is not the same in the English and in the German version.

**Comment by koppor** [comment]
Isn't it also a different font? Why should it be the same? Ludewig says (in
his Leitfaden-Book) that German sentences are longer and therefore the text
body should be wider than in English...

**Comment by koppor** [comment]
Although Ludewig recommends to use [Palatino](https://de.wikipedia.org/wiki/Palatino), we switch to Times Roman for both templates. With the [newtx](https://ctan.org/pkg/newtx) packages, it looks good and there is no need to use [Linux Libertine](https://de.wikipedia.org/wiki/Linux_Libertine).

**Comment by koppor** [comment]
Try out [Release 2.2.0](https://github.com/latextemplates/scientific-thesis-template/releases/tag/2.2.0)
