### ISSUE TITLE
Add ADR: latexdemo vs. tcolorbox

### ISSUE THREAD

**Issue by koppor** [latextemplates/scientific-thesis-template#82]
[tcolorbox](https://www.ctan.org/pkg/tcolorbox) also supports code and rendering. Seems to look better than [latexdemo](https://www.ctan.org/pkg/latexdemo).

- Compare them
- Choose one
- If tcolorbox is chosen: rewrite examples
- Add [ADR](https://github.com/adr/madr)

**Comment by diehlpk** [comment]
I am not sure if the tcolorbox can handle floating environments, e.g. figures or tables, so I do not see real benefits for showing the equations only. It seems that the new proposed package is more fancy.

**Comment by koppor** [comment]
In https://github.com/latextemplates/generator-latex-template/pull/9, I began to create an ADR.

I think, both latexdemo and tcolorbox cannot handle floating enviroments. [showexpl](https://www.ctan.org/pkg/showexpl) can since yesterday :tada: --> https://github.com/rolfn/showexpl/issues/1

**Comment by koppor** [comment]
We need a custom environemnt: See the ADR in generator-latex-template: https://github.com/latextemplates/generator-latex-template/blob/master/docs/adr/0005-custom-example-environment.md.
