### ISSUE TITLE
master missing dependency for font "TeX Gyre Heros"?

### ISSUE THREAD

**Issue by kmindi** [latextemplates/scientific-thesis-template#88]
I have not looked into it, but installing the "TeX Gyre Heros" or similar via MikTex solved the issue. Don't know if this is a missing package dependency/declaration in the template.

**Comment by koppor** [comment]
Thank you for the hint. In https://github.com/latextemplates/scientific-thesis-template/commit/9c250e1887c63754ac652f4da49c8d453a311861, I added it to the installation instructions for MiKTeX: https://github.com/latextemplates/scientific-thesis-template/blob/master/README.md#recommended-setup-of-miktex

    Execute mpm --install=tex-gyre (to resolve fontspec error: "font-not-found", \setmainfont{TeX Gyre Termes})
    Execute mpm --install=tex-gyre-math

**Comment by kmindi** [comment]
Can't this be done using `\RequirePackage`/`\usepackage` (in MikTex the font then would be automatically downloaded, at least if it has been configured that way)? Anyway I tried it quickly and it seems it does not work for those packages, but I don't know why ... (`tex-gyre-heros`, `tex-gyre-termes` and `tex-gyre-math`)

**Comment by koppor** [comment]
We use lualatex now. Font selection is done using `\setmainfont` (see https://github.com/latextemplates/scientific-thesis-template/blob/9c250e1887c63754ac652f4da49c8d453a311861/config.tex#L744).

Fonts are not provided via a latex (`usepackage`) anymore, but as plain fonts (CTAN package). (See also https://tex.stackexchange.com/a/247533/9075 for an explanation on the confusion of latex package vs. CTAN package). MiKTeX allows for auto-installation of latex packages only, not for CTAN packages.
